### ISSUE TITLE
Horizontally scroll between segments ?

### ISSUE THREAD

**Issue by qbraksa** [aryaxt/ScrollPager#11]
Hi, 

I really love what you did so far with the ScrollPager, it's really well implemented & easy to understand.

One **question** though :  

+ Is it possible to horizontally scroll between the segments if there is too many ? 

Thanks.

**Comment by aryaxt** [comment]
@qbraksa Glad you found it helpful. It currently doesn't support that, but should't be too hard to implement it

**Comment by qbraksa** [comment]
Alright, cool ! I'll see what I can do!
