### ISSUE TITLE
two compile errors with Swift 2.0

### ISSUE THREAD

**Issue by JoeShi** [aryaxt/ScrollPager#16]
Thanks for the lib, really handy. there are two compile errors with swift 2.0

![image](https://cloud.githubusercontent.com/assets/2173635/11614056/31534000-9c71-11e5-9f1c-9bee0972383c.png)

![image](https://cloud.githubusercontent.com/assets/2173635/11614055/21ebd082-9c71-11e5-8b1d-f57adbe18be7.png)

**Comment by aryaxt** [comment]
I believe those are 2.1 errors
#15

**Comment by JoeShi** [comment]
yes, true. Actually, I found it is fixed in the master branch. I use cocoapods and refer to version 0.4, it will show me the error. What if I refer to the master branch, the error gone. 

It will be very grateful to update the pod spec.

**Comment by aryaxt** [comment]
yeah master was updated to work with 2.0, but it's broken on 2.1.
As soon as that PR is fixed and merged will release to cocoapods

**Comment by JoeShi** [comment]
OK, thank you very much.

**Comment by aryaxt** [comment]
This is fixed and pushed to cocoapods
