### ISSUE TITLE
Add ViewControllers to ScrollPager

### ISSUE THREAD

**Issue by thefronter** [aryaxt/ScrollPager#18]
How I can add a viewController to the ScrollPager? In my case i have a collectionView In a view controller and i want load like a view in the scrollPager.  I do this, but it shows a with view.

let viewController = ViewController()
        let fourthView = viewController.view
        scrollPager.delegate = self
        scrollPager.addSegmentsWithTitlesAndViews([
            ("Profile", thirdView),
            ("One More", fourthView)
            ])
        scrollPager.delegate = self

Can u help me? I really need this scrollPager

**Comment by aryaxt** [comment]
each ViewController has a view, add it's view to the scrollPager
```scrollPager.addSegmentsWithTitlesAndViews([
  ("Home", homeViewController.view)
])```

**Comment by thefronter** [comment]
Yes, but when i do this, the scrollPager shows an empty view. It dont load the view of the viewController. Do u have somo example using it? 

Sorry for the inconvenience

**Comment by aryaxt** [comment]
mmm not sure, but using the view of a controller is exactly the same as using any other view.
I would suggest running view debugger and see if the views are showing up, and changing background color of the views to debug it.

**Comment by thefronter** [comment]
I am a litle noob. If i load a view from a xib file, its works. But i ask if is posible load from a viewController in a StoryBoard.. How I can hold a reference from the controllers?

**Comment by aryaxt** [comment]
There is amethod named instantiateviewcontrollerwithidentifier on
uistoryboard class. If you google you will find it

**Comment by thefronter** [comment]
i got it. Ok with this method only can load a view, but the code of that view isnt load rigth? If i have a button and the button have an action, that action never executed, istn it?
Regards and thanks

**Comment by wongzigii** [comment]
@thefronter  Hey, how did you finally set up with viewcontrollers ? Can you provide some code snippets?
