### ISSUE TITLE
build failed ):

### ISSUE THREAD

**Issue by kunggea** [aryaxt/ScrollPager#2]
build failed ):
swift method addSegments conflicts with OC selector,

**Comment by aryaxt** [comment]
That's an error using it with Swift 1.2, will update the code

**Comment by kunggea** [comment]
thanks
change the last mothod name can pass this issue

Aryan Ghassemi <notifications@github.com>于2015年4月23日星期四写道：

**Comment by aryaxt** [comment]
Thanks, it's fixed and pushed

**Comment by kunggea** [comment]
thanks  great lib!

Aryan Ghassemi <notifications@github.com>于2015年4月23日星期四写道：
