### ISSUE TITLE
Crash while setting up without InterfaceBuilder

### ISSUE THREAD

**Issue by wongzigii** [aryaxt/ScrollPager#20]
I am using ScrollPager in code and trying to set up with my viewControllers. 
These controllers are using AutoLayout to setup constraints.

    let library = ImagePickerController()
  
    let photo = CameraViewController()
  
    lazy var bottomScrollPager: ScrollPager = { [unowned self] in
      let scrollPager = ScrollPager()
      scrollPager.translatesAutoresizingMaskIntoConstraints = false
      scrollPager.addSegmentsWithTitlesAndViews([("LIBRARY", self.library.view),("PHOTO", self.photo.view),("VIDEO", UIView())])
      scrollPager.delegate = self
      return scrollPager
    }()

But the views did not appear. Also application crashed:

> fatal error: unexpectedly found nil while unwrapping an Optional value

Error shows on the `for view in scrollView!.subviews` line;

    private func addViews(segmentViews: [UIView]) {
		for view in scrollView!.subviews {
			view.removeFromSuperview()
		}
		
		for i in 0..<segmentViews.count {
			let view = segmentViews[i]
			scrollView!.addSubview(view)
			views.append(view)
		}
	}

 I noticed that the `scrollView` is optional which marked with `?` and when I am not in IB or xib. 
I guess that the reason why the crash happened?

**Comment by wongzigii** [comment]
Can you provide a demo  shipping with viewControllers in code? Thanks.

**Comment by Lyansun** [comment]
If you are completely using the code, you need to create a scrollView   
scrollPager.scrollView = scrollView

**Comment by aryaxt** [comment]
You don't need a scrollView that's optional
```
let sp = ScrollPager()
sp.addSegmentsWithTitles(["1", "2", "3"])
sp.frame = CGRectMake(0, 300, view.frame.size.width, 60)
sp.indicatorColor = UIColor.blackColor()
view.addSubview(sp)
```

Can you please post the crash log?

**Comment by wongzigii** [comment]
I've just uploaded a sample project. Please check out: https://github.com/wongzigii/scrollpagercrash

**Comment by aryaxt** [comment]
so you are using the method that adds pages to a scrollView and the scrollView is not set.
Will update the code to avoid a crash but if you need paging functionality you should have a scrollView which is set on the scrollView property of the scrollPager

**Comment by aryaxt** [comment]
version 0.7 is in with the fix, but you still need to use a UIScrollview when you need paging functionality

**Comment by wongzigii** [comment]
Thanks! @aryaxt

**Comment by aryaxt** [comment]
🍻
