### ISSUE TITLE
add pre-design view

### ISSUE THREAD

**Issue by pranavpari** [aryaxt/ScrollPager#27]
Hello,
How I can use pre-design view instead of create it run time?

**Comment by aryaxt** [comment]
just add a view to storyboard and in inspector change its class from UIView to ScrollPager

**Comment by pranavpari** [comment]
no not like that. I have 3 UIViews in my viewcontroller it self. I want add these views in scrollpager. if I create view at run time it is working but I am not able to use my pre-design view in scrollpager.

**Comment by aryaxt** [comment]
Simply add your views in IB, assign outlets to them, and at runtime set them as views of the scrollpager
![screen shot 2016-09-08 at 8 57 11 am](https://cloud.githubusercontent.com/assets/3460069/18356626/554db688-75a2-11e6-903e-383ea56c81e2.png)
