### ISSUE TITLE
in iPad View not showing using scroll pager

### ISSUE THREAD

**Issue by ravikantchadda** [aryaxt/ScrollPager#28]

**Comment by shawn-shen** [comment]
Same here,
@aryaxt Any clarifications on this ticket? Loading the sample project with iPad pro simulator...the views are not rendered properly.
![screen shot 2017-03-14 at 12 07 14 pm](https://cloud.githubusercontent.com/assets/15338860/23881479/c9895c74-08ae-11e7-8e77-0cf88ac54fef.png)

**Comment by aryaxt** [comment]
@ravikantchadda @shawn-shen That was an issue with constraints in the demo project and not with the library. Thanks for reporting, pushed fixes of the demo and it should appear correctly on iPad now.

Thanks 🍻
