### ISSUE TITLE
problem to change background color of scrollview

### ISSUE THREAD

**Issue by mabebrahimi** [aryaxt/ScrollPager#29]
helllo 

in have a problem with this awesome library man ...
my problem is when i use this library i cant change the background color of scrollview ... is this a issue or do you have any idea ???? 

sorry for my bad english and thank you :)

**Comment by aryaxt** [comment]
The library does not change the background color of the scrollView. The background of the scrollView is usually not visible either, so maybe it's being covered by the views? Try setting clear color on views you are passing to it
