### ISSUE TITLE
addSegmentsWithTitlesAndViews doesn't appear in Objective-c Header file

### ISSUE THREAD

**Issue by Krystel** [aryaxt/ScrollPager#3]
When using the ScrollPager class in an Objective-C project, the below function:
public func addSegmentsWithTitlesAndViews(segments: [(title: String, view: UIView)])
doesn't appear in the header file created by xcode (addSegmentsWithTitles is included and works perfectly).

Any idea why? Or if there's a turnaround to adding different/same subview in all scroll indexes ?

Thank you

![screen shot 2015-04-29 at 4 27 24 pm](https://cloud.githubusercontent.com/assets/5189251/7391883/c04e1b42-ee8c-11e4-9a08-d29d50615053.png)

**Comment by aryaxt** [comment]
That's correct because it's using Tuples, and tuples are not supported in Objective C. Create an extension with an objective c compatible method:
```swift
extension ScrollPager {
	
	func addSegments(titles: [String], views: [UIView]) {
		var tuples: [(title: String, view: UIView)] = []
		
		for i in 0..<titles.count {
			tuples.append(title: titles[i], view: views[i])
		}
		
		addSegmentsWithTitlesAndViews(tuples)
	}
}
```

**Comment by Krystel** [comment]
Ahh alright.
It works like a charm! 
Thank you
