### ISSUE TITLE
when setSelectedIndex:1:true:true App crash 

### ISSUE THREAD

**Issue by Meseery** [aryaxt/ScrollPager#4]
When `setSelectedIndex` is called, the error :Array is out of index is thrown, when i debugged your code, i found `view`array doesn't have any views also the `buttons` array !

**Comment by aryaxt** [comment]
Can't reproduce. Are you calling it after setting segments?

**Comment by Meseery** [comment]
yes, it's strange not to retain views and buttons array , here's the debug console:
![screen shot 2015-04-30 at 5 36 44 am](https://cloud.githubusercontent.com/assets/3482174/7405991/c6fc1d00-ef03-11e4-85e8-b1e6e33f85f1.png)

**Comment by Meseery** [comment]
Any updates ?!

**Comment by aryaxt** [comment]
I can't reproduce, do you mind sending a sample?

**Comment by Meseery** [comment]
The issue is the `Views` and `Buttons` arrays are emptied up after loading, as you see in the console screenshot ,so that calling `setSelectedIndex:1:true:true` isn't effective !

**Comment by aryaxt** [comment]
I see the crash but I have a feeling that you are not setting it up correctly? Can you cause this crash on the demo project?

**Comment by Meseery** [comment]
The Demo project setup the `Scrollpager` views programmatically, but i use nib files instead !

**Comment by aryaxt** [comment]
Sorry dude, can't help if the bug is not reproducable in the demo, and you don't have any sample code to reproduce it.
