### ISSUE TITLE
Not possible to add a view controller's view?

### ISSUE THREAD

**Issue by kosicki123** [aryaxt/ScrollPager#5]
Hi, how can I add a view that belongs to a view controller? 
If I do that, when I interact with something it crashes without exception.
You know how to make some work around? 
I really want to use this on my project.

Thanks

**Comment by aryaxt** [comment]
You should be able to do it.
It's probably crashing because you are not holding a strong reference to the controllers. The controller gets released but the view doesn't because scrollpager is retaining them, so when you interact with the views it crashes

**Comment by kosicki123** [comment]
Thanks a lot, you're so right, sorry for the noob question!
